version: '3.8'

services:
  timelapse_cam1:
    build: .
    restart: unless-stopped
    volumes:
      - /var/cctv/cam1:/videos/input
      - /var/cctv/cam1-timelapse:/videos/output
    devices:
      - /dev/dri:/dev/dri

  timelapse_cam2:
    build: .
    restart: unless-stopped
    volumes:
      - /var/cctv/cam2:/videos/input
      - /var/cctv/cam2-timelapse:/videos/output
    devices:
      - /dev/dri:/dev/dri
